@@ .. @@
 -- 创建 task_info 表
 CREATE TABLE IF NOT EXISTS public.task_info (
-  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   created_at timestamp with time zone DEFAULT now() NOT NULL,
   uuid uuid NOT NULL REFERENCES public.user_info(uuid) ON DELETE CASCADE,
   task_id bigint,
@@ .. @@
   model_params jsonb DEFAULT '{}'::jsonb
 );

+-- 添加主键约束（使用 uuid 和 task_id 的组合）
+ALTER TABLE public.task_info ADD CONSTRAINT task_info_pkey PRIMARY KEY (uuid, task_id);
+
 -- 启用 RLS