/*
  # 创建任务信息表

  1. 新建表
    - `task_info` 表用于存储用户任务和文件夹信息
    - 支持文件夹和任务的统一存储
    - 使用 JSONB 存储聊天历史和模型参数

  2. 安全性
    - 启用 RLS
    - 添加用户访问策略
*/

-- 创建 task_info 表
CREATE TABLE IF NOT EXISTS public.task_info (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  uuid uuid NOT NULL REFERENCES public.user_info(uuid) ON DELETE CASCADE,
  task_id bigint,
  task_folder_name text,
  task_name text,
  system_prompt text,
  chatinfo jsonb DEFAULT '[]'::jsonb,
  model_params jsonb DEFAULT '{}'::jsonb
);

-- 启用 RLS
ALTER TABLE public.task_info ENABLE ROW LEVEL SECURITY;

-- 添加 RLS 策略
CREATE POLICY "Users can read own task_info"
  ON public.task_info
  FOR SELECT
  TO authenticated
  USING (auth.uid() = uuid);

CREATE POLICY "Users can insert own task_info"
  ON public.task_info
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = uuid);

CREATE POLICY "Users can update own task_info"
  ON public.task_info
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = uuid)
  WITH CHECK (auth.uid() = uuid);

CREATE POLICY "Users can delete own task_info"
  ON public.task_info
  FOR DELETE
  TO authenticated
  USING (auth.uid() = uuid);

-- 添加索引优化查询性能
CREATE INDEX IF NOT EXISTS idx_task_info_uuid ON public.task_info (uuid);
CREATE INDEX IF NOT EXISTS idx_task_info_task_id ON public.task_info (task_id);
CREATE INDEX IF NOT EXISTS idx_task_info_folder_name ON public.task_info (task_folder_name);

-- 添加 GIN 索引用于 JSONB 字段
CREATE INDEX IF NOT EXISTS idx_task_info_chatinfo_gin ON public.task_info USING gin (chatinfo);
CREATE INDEX IF NOT EXISTS idx_task_info_model_params_gin ON public.task_info USING gin (model_params);

-- 添加表和字段注释
COMMENT ON TABLE public.task_info IS '存储用户任务和文件夹信息';
COMMENT ON COLUMN public.task_info.uuid IS '用户ID，关联到 user_info(uuid)';
COMMENT ON COLUMN public.task_info.task_id IS '任务唯一ID，NULL 表示这是文件夹记录';
COMMENT ON COLUMN public.task_info.task_folder_name IS '文件夹名称';
COMMENT ON COLUMN public.task_info.task_name IS '任务文件名';
COMMENT ON COLUMN public.task_info.system_prompt IS '当前任务的系统提示词内容';
COMMENT ON COLUMN public.task_info.chatinfo IS '聊天历史记录，JSONB 数组格式';
COMMENT ON COLUMN public.task_info.model_params IS '模型参数配置，JSONB 对象格式';