/*
  # Add unauthenticated usage tracking and app settings

  1. New Tables
    - `unauthenticated_usage` - Track daily message usage for unauthenticated users
    - `app_settings` - Store configurable application settings

  2. Security
    - No RLS needed for these tables as they're managed by Edge Functions
    - Add indexes for performance

  3. Default Configuration
    - Set daily message limit to 10 for unauthenticated users
*/

-- Create unauthenticated usage tracking table
CREATE TABLE IF NOT EXISTS public.unauthenticated_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unauth_user_id text NOT NULL,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  message_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(unauth_user_id, usage_date)
);

-- Create app settings table
CREATE TABLE IF NOT EXISTS public.app_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_unauth_usage_user_date ON public.unauthenticated_usage (unauth_user_id, usage_date);
CREATE INDEX IF NOT EXISTS idx_unauth_usage_date ON public.unauthenticated_usage (usage_date);

-- Insert default settings
INSERT INTO public.app_settings (key, value, description) 
VALUES 
  ('daily_unauth_message_limit', '10', 'Daily message limit for unauthenticated users'),
  ('unauth_model_name', '"gpt-3.5-turbo"', 'Default AI model for unauthenticated users'),
  ('unauth_max_tokens', '1000', 'Maximum tokens per response for unauthenticated users'),
  ('unauth_temperature', '0.7', 'Temperature setting for unauthenticated users')
ON CONFLICT (key) DO NOTHING;

-- Add table comments
COMMENT ON TABLE public.unauthenticated_usage IS 'Track daily message usage for unauthenticated users';
COMMENT ON TABLE public.app_settings IS 'Store configurable application settings';
COMMENT ON COLUMN public.unauthenticated_usage.unauth_user_id IS 'Hash of IP + User Agent to identify unauthenticated users';
COMMENT ON COLUMN public.unauthenticated_usage.usage_date IS 'Date of usage (resets daily)';
COMMENT ON COLUMN public.unauthenticated_usage.message_count IS 'Number of messages sent on this date';